codecov:
  require_ci_to_pass: yes
  notify:
    require_ci_to_pass: yes
    after_n_builds: 2
  coverage:
    round: down
    precision: 2
    status:
      project:
        default:
          target: auto
